/**
 * Comprehensive RouterOS Menu Catalog — bagian E (system console s.d. zerotier peer hint).
 * Diekstrak dari korpus bantuan RouterOS (ros-help.db).
 */
export const ROUTEROS_MENUS_E: string[] = [
  "/system console",
  "/system console screen",
  "/system default-configuration",
  "/system default-configuration caps-mode-script",
  "/system default-configuration custom-script",
  "/system default-configuration script",
  "/system device-mode",
  "/system gps",
  "/system health",
  "/system health settings",
  "/system history",
  "/system identity",
  "/system leds",
  "/system leds settings",
  "/system license",
  "/system logging",
  "/system logging action",
  "/system note",
  "/system ntp",
  "/system ntp client",
  "/system ntp client servers",
  "/system ntp key",
  "/system ntp server",
  "/system package",
  "/system package local-update",
  "/system package local-update mirror",
  "/system package local-update update-package-source",
  "/system package update",
  "/system regulatory",
  "/system resource",
  "/system resource cpu",
  "/system resource hardware",
  "/system resource hardware usb-settings",
  "/system resource irq",
  "/system routerboard",
  "/system routerboard mode-button",
  "/system routerboard reset-button",
  "/system routerboard settings",
  "/system routerboard usb",
  "/system routerboard wps-button",
  "/system rtrace",
  "/system scheduler",
  "/system script",
  "/system script environment",
  "/system script job",
  "/system special-login",
  "/system ups",
  "/system watchdog",
  "/task",
  "/terminal",
  "/tool",
  "/tool bandwidth-server",
  "/tool bandwidth-server session",
  "/tool bandwidth-test",
  "/tool calea",
  "/tool e-mail",
  "/tool flood-ping",
  "/tool graphing",
  "/tool graphing interface",
  "/tool graphing queue",
  "/tool graphing resource",
  "/tool ip-scan",
  "/tool mac-server",
  "/tool mac-server mac-winbox",
  "/tool mac-server ping",
  "/tool mac-server sessions",
  "/tool netwatch",
  "/tool ping",
  "/tool profile",
  "/tool romon",
  "/tool romon port",
  "/tool sms",
  "/tool sms inbox",
  "/tool sniffer",
  "/tool sniffer connection",
  "/tool sniffer host",
  "/tool sniffer packet",
  "/tool sniffer protocol",
  "/tool speed-test",
  "/tool traceroute",
  "/tool traffic-generator",
  "/tool traffic-generator packet-template",
  "/tool traffic-generator port",
  "/tool traffic-generator raw-packet-template",
  "/tool traffic-generator stats",
  "/tool traffic-generator stats latency-distribution",
  "/tool traffic-generator stats port",
  "/tool traffic-generator stats raw",
  "/tool traffic-generator stats stream",
  "/tool traffic-generator stream",
  "/tool traffic-monitor",
  "/tool wol",
  "/tr069-client",
  "/user",
  "/user aaa",
  "/user active",
  "/user group",
  "/user settings",
  "/user ssh-keys",
  "/user ssh-keys private",
  "/user-manager",
  "/user-manager advanced",
  "/user-manager attribute",
  "/user-manager database",
  "/user-manager limitation",
  "/user-manager payment",
  "/user-manager profile",
  "/user-manager profile-limitation",
  "/user-manager router",
  "/user-manager session",
  "/user-manager user",
  "/user-manager user group",
  "/user-manager user-profile",
  "/zerotier",
  "/zerotier controller",
  "/zerotier controller member",
  "/zerotier interface",
  "/zerotier peer",
  "/zerotier peer hint",
];
