/**
 * Comprehensive RouterOS Menu Catalog — bagian C (ip dns static s.d. mpls interface).
 * Diekstrak dari korpus bantuan RouterOS (ros-help.db).
 */
export const ROUTEROS_MENUS_C: string[] = [
  "/ip dns static",
  "/ip firewall",
  "/ip firewall address-list",
  "/ip firewall calea",
  "/ip firewall connection",
  "/ip firewall connection tracking",
  "/ip firewall filter",
  "/ip firewall layer7-protocol",
  "/ip firewall mangle",
  "/ip firewall nat",
  "/ip firewall raw",
  "/ip firewall service-port",
  "/ip hotspot",
  "/ip hotspot active",
  "/ip hotspot cookie",
  "/ip hotspot host",
  "/ip hotspot ip-binding",
  "/ip hotspot profile",
  "/ip hotspot service-port",
  "/ip hotspot user",
  "/ip hotspot user profile",
  "/ip hotspot walled-garden",
  "/ip hotspot walled-garden ip",
  "/ip ipsec",
  "/ip ipsec active-peers",
  "/ip ipsec identity",
  "/ip ipsec installed-sa",
  "/ip ipsec key",
  "/ip ipsec key psk",
  "/ip ipsec key qkd",
  "/ip ipsec key rsa",
  "/ip ipsec mode-config",
  "/ip ipsec peer",
  "/ip ipsec policy",
  "/ip ipsec policy group",
  "/ip ipsec profile",
  "/ip ipsec proposal",
  "/ip ipsec settings",
  "/ip ipsec statistics",
  "/ip kid-control",
  "/ip kid-control device",
  "/ip media",
  "/ip media settings",
  "/ip nat-pmp",
  "/ip nat-pmp interfaces",
  "/ip neighbor",
  "/ip neighbor discovery",
  "/ip neighbor discovery-settings",
  "/ip neighbor lldp",
  "/ip packing",
  "/ip pool",
  "/ip pool used",
  "/ip proxy",
  "/ip proxy access",
  "/ip proxy cache",
  "/ip proxy cache-contents",
  "/ip proxy connections",
  "/ip proxy direct",
  "/ip proxy inserts",
  "/ip proxy lookups",
  "/ip proxy refreshes",
  "/ip reverse-proxy",
  "/ip route",
  "/ip service",
  "/ip service webserver",
  "/ip settings",
  "/ip smb",
  "/ip smb shares",
  "/ip smb users",
  "/ip socks",
  "/ip socks access",
  "/ip socks connections",
  "/ip socks users",
  "/ip socksify",
  "/ip ssh",
  "/ip tftp",
  "/ip tftp settings",
  "/ip traffic-flow",
  "/ip traffic-flow ipfix",
  "/ip traffic-flow target",
  "/ip upnp",
  "/ip upnp interfaces",
  "/ip vrf",
  "/ipv6",
  "/ipv6 address",
  "/ipv6 dhcp-client",
  "/ipv6 dhcp-client option",
  "/ipv6 dhcp-relay",
  "/ipv6 dhcp-relay option",
  "/ipv6 dhcp-relay routes",
  "/ipv6 dhcp-server",
  "/ipv6 dhcp-server binding",
  "/ipv6 dhcp-server option",
  "/ipv6 dhcp-server option sets",
  "/ipv6 firewall",
  "/ipv6 firewall address-list",
  "/ipv6 firewall connection",
  "/ipv6 firewall filter",
  "/ipv6 firewall mangle",
  "/ipv6 firewall nat",
  "/ipv6 firewall raw",
  "/ipv6 nd",
  "/ipv6 nd prefix",
  "/ipv6 nd prefix default",
  "/ipv6 nd proxy",
  "/ipv6 nd settings",
  "/ipv6 neighbor",
  "/ipv6 pool",
  "/ipv6 pool used",
  "/ipv6 route",
  "/ipv6 settings",
  "/led",
  "/log",
  "/lte",
  "/mpls",
  "/mpls forwarding-table",
  "/mpls interface",
];
