/**
 * Comprehensive RouterOS Menu Catalog — bagian B (interface mesh fdb s.d. ip dns forwarders).
 * Diekstrak dari korpus bantuan RouterOS (ros-help.db).
 */
export const ROUTEROS_MENUS_B: string[] = [
  "/interface mesh fdb",
  "/interface mesh port",
  "/interface monitor-traffic",
  "/interface ovpn-client",
  "/interface ovpn-server",
  "/interface ovpn-server server",
  "/interface ppp-client",
  "/interface ppp-server",
  "/interface pppoe-client",
  "/interface pppoe-server",
  "/interface pppoe-server server",
  "/interface pptp-client",
  "/interface pptp-server",
  "/interface pptp-server server",
  "/interface sstp-client",
  "/interface sstp-server",
  "/interface sstp-server server",
  "/interface veth",
  "/interface vlan",
  "/interface vpls",
  "/interface vrrp",
  "/interface vxlan",
  "/interface vxlan fdb",
  "/interface vxlan vteps",
  "/interface wifi",
  "/interface wifi aaa",
  "/interface wifi access-list",
  "/interface wifi cap",
  "/interface wifi capsman",
  "/interface wifi capsman remote-cap",
  "/interface wifi channel",
  "/interface wifi configuration",
  "/interface wifi datapath",
  "/interface wifi interworking",
  "/interface wifi network",
  "/interface wifi network radio",
  "/interface wifi provisioning",
  "/interface wifi radio",
  "/interface wifi radio settings",
  "/interface wifi registration-table",
  "/interface wifi security",
  "/interface wifi security multi-passphrase",
  "/interface wifi steering",
  "/interface wifi steering neighbor-group",
  "/interface wifiwave2",
  "/interface wireguard",
  "/interface wireguard peers",
  "/interface wireless",
  "/interface wireless access-list",
  "/interface wireless align",
  "/interface wireless cap",
  "/interface wireless channels",
  "/interface wireless connect-list",
  "/interface wireless frequency-monitor",
  "/interface wireless info",
  "/interface wireless interworking-profiles",
  "/interface wireless manual-tx-power-table",
  "/interface wireless nstreme",
  "/interface wireless nstreme-dual",
  "/interface wireless registration-table",
  "/interface wireless security-profiles",
  "/interface wireless sniffer",
  "/interface wireless sniffer packet",
  "/interface wireless snooper",
  "/interface wireless wds",
  "/interface wlan",
  "/iot",
  "/iot bluetooth",
  "/iot bluetooth advertisers",
  "/iot bluetooth advertisers ad-structures",
  "/iot bluetooth connections",
  "/iot bluetooth connections async-data",
  "/iot bluetooth connections characteristics",
  "/iot bluetooth peripheral-devices",
  "/iot bluetooth scanners",
  "/iot bluetooth scanners advertisements",
  "/iot bluetooth whitelist",
  "/iot lora",
  "/iot lora channels",
  "/iot lora joineui",
  "/iot lora netid",
  "/iot lora radios",
  "/iot lora servers",
  "/iot lora traffic",
  "/iot lora traffic options",
  "/iot modbus",
  "/iot modbus security-rules",
  "/iot mqtt",
  "/iot mqtt brokers",
  "/iot mqtt subscriptions",
  "/iot mqtt subscriptions recv",
  "/iot wiliot",
  "/iot wiliot bluetooth-traffic",
  "/iot wiliot mqtt-traffic",
  "/iot wiliot options",
  "/iot wiliot servers",
  "/ip",
  "/ip address",
  "/ip arp",
  "/ip cloud",
  "/ip cloud advanced",
  "/ip cloud back-to-home-file",
  "/ip cloud back-to-home-file settings",
  "/ip cloud back-to-home-user",
  "/ip dhcp-client",
  "/ip dhcp-client option",
  "/ip dhcp-relay",
  "/ip dhcp-server",
  "/ip dhcp-server alert",
  "/ip dhcp-server config",
  "/ip dhcp-server lease",
  "/ip dhcp-server matcher",
  "/ip dhcp-server network",
  "/ip dhcp-server option",
  "/ip dhcp-server option sets",
  "/ip dns",
  "/ip dns adlist",
  "/ip dns cache",
  "/ip dns cache all",
  "/ip dns forwarders",
];
