/**
 * Comprehensive RouterOS Menu Catalog — bagian A (app s.d. interface mesh).
 * Diekstrak dari korpus bantuan RouterOS (ros-help.db).
 */
export const ROUTEROS_MENUS_A: string[] = [
  "/app",
  "/app network",
  "/app settings",
  "/backup",
  "/caps-man",
  "/caps-man aaa",
  "/caps-man access-list",
  "/caps-man actual-interface-configuration",
  "/caps-man channel",
  "/caps-man configuration",
  "/caps-man datapath",
  "/caps-man interface",
  "/caps-man manager",
  "/caps-man manager interface",
  "/caps-man provisioning",
  "/caps-man radio",
  "/caps-man rates",
  "/caps-man registration-table",
  "/caps-man remote-cap",
  "/caps-man security",
  "/certificate",
  "/certificate builtin",
  "/certificate crl",
  "/certificate scep-server",
  "/certificate scep-server otp",
  "/certificate scep-server ra",
  "/certificate scep-server requests",
  "/certificate settings",
  "/console",
  "/console settings",
  "/container",
  "/container config",
  "/container envs",
  "/container layers",
  "/container log",
  "/container mounts",
  "/disk",
  "/disk btrfs",
  "/disk btrfs filesystem",
  "/disk btrfs subvolume",
  "/disk btrfs transfer",
  "/disk settings",
  "/dude",
  "/dude agent",
  "/dude device",
  "/dude device-type",
  "/dude notification",
  "/dude probe",
  "/dude ros",
  "/dude ros address",
  "/dude ros arp",
  "/dude ros health",
  "/dude ros interface",
  "/dude ros lease",
  "/dude ros neighbor",
  "/dude ros queue",
  "/dude ros registration-table",
  "/dude ros resource",
  "/dude ros route",
  "/dude ros routerboard",
  "/dude service",
  "/dude settings",
  "/environment",
  "/export",
  "/file",
  "/file rsync-daemon",
  "/file sync",
  "/gps",
  "/hotspot",
  "/import",
  "/interface",
  "/interface 6to4",
  "/interface bonding",
  "/interface bridge",
  "/interface bridge calea",
  "/interface bridge filter",
  "/interface bridge host",
  "/interface bridge mdb",
  "/interface bridge msti",
  "/interface bridge nat",
  "/interface bridge port",
  "/interface bridge port mst-override",
  "/interface bridge settings",
  "/interface bridge vlan",
  "/interface bridge vlan mvrp",
  "/interface detect-internet",
  "/interface detect-internet state",
  "/interface dot1x",
  "/interface dot1x client",
  "/interface dot1x server",
  "/interface dot1x server active",
  "/interface dot1x server state",
  "/interface eoip",
  "/interface eoipv6",
  "/interface ethernet",
  "/interface ethernet switch",
  "/interface ethernet switch host",
  "/interface ethernet switch port",
  "/interface ethernet switch port-isolation",
  "/interface ethernet switch rule",
  "/interface ethernet switch vlan",
  "/interface gre",
  "/interface gre6",
  "/interface ipip",
  "/interface ipipv6",
  "/interface l2tp-client",
  "/interface l2tp-ether",
  "/interface l2tp-server",
  "/interface l2tp-server server",
  "/interface list",
  "/interface list member",
  "/interface lte",
  "/interface lte apn",
  "/interface lte esim",
  "/interface lte settings",
  "/interface macsec",
  "/interface macsec profile",
  "/interface macvlan",
  "/interface mesh",
];
