/**
 * Comprehensive RouterOS Menu Catalog — bagian D (mpls ldp s.d. system clock manual).
 * Diekstrak dari korpus bantuan RouterOS (ros-help.db).
 */
export const ROUTEROS_MENUS_D: string[] = [
  "/mpls ldp",
  "/mpls ldp accept-filter",
  "/mpls ldp advertise-filter",
  "/mpls ldp interface",
  "/mpls ldp local-mapping",
  "/mpls ldp neighbor",
  "/mpls ldp remote-mapping",
  "/mpls mangle",
  "/mpls settings",
  "/mpls traffic-eng",
  "/mpls traffic-eng flow",
  "/mpls traffic-eng interface",
  "/mpls traffic-eng path",
  "/mpls traffic-eng tunnel",
  "/openflow",
  "/openflow flow",
  "/openflow group",
  "/openflow meter",
  "/openflow port",
  "/port",
  "/port remote-access",
  "/ppp",
  "/ppp aaa",
  "/ppp active",
  "/ppp l2tp-secret",
  "/ppp profile",
  "/ppp secret",
  "/queue",
  "/queue interface",
  "/queue priority",
  "/queue simple",
  "/queue tree",
  "/queue type",
  "/radius",
  "/radius incoming",
  "/routing",
  "/routing bfd",
  "/routing bfd configuration",
  "/routing bfd session",
  "/routing bgp",
  "/routing bgp advertisements",
  "/routing bgp connection",
  "/routing bgp evpn",
  "/routing bgp instance",
  "/routing bgp session",
  "/routing bgp template",
  "/routing bgp vpls",
  "/routing bgp vpn",
  "/routing fantasy",
  "/routing filter",
  "/routing filter chain",
  "/routing filter community-ext-list",
  "/routing filter community-large-list",
  "/routing filter community-list",
  "/routing filter num-list",
  "/routing filter rule",
  "/routing filter select-rule",
  "/routing gmp",
  "/routing id",
  "/routing igmp-proxy",
  "/routing igmp-proxy interface",
  "/routing igmp-proxy mfc",
  "/routing isis",
  "/routing isis instance",
  "/routing isis interface",
  "/routing isis interface-template",
  "/routing isis lsp",
  "/routing isis neighbor",
  "/routing nexthop",
  "/routing ospf",
  "/routing ospf area",
  "/routing ospf area range",
  "/routing ospf instance",
  "/routing ospf interface",
  "/routing ospf interface-template",
  "/routing ospf lsa",
  "/routing ospf neighbor",
  "/routing ospf static-neighbor",
  "/routing pimsm",
  "/routing pimsm bsr",
  "/routing pimsm bsr candidate",
  "/routing pimsm bsr rp-candidate",
  "/routing pimsm bsr rp-set",
  "/routing pimsm igmp-interface-template",
  "/routing pimsm instance",
  "/routing pimsm interface",
  "/routing pimsm interface-template",
  "/routing pimsm neighbor",
  "/routing pimsm static-rp",
  "/routing pimsm uib-g",
  "/routing pimsm uib-sg",
  "/routing rip",
  "/routing rip instance",
  "/routing rip interface",
  "/routing rip interface-template",
  "/routing rip keys",
  "/routing rip neighbor",
  "/routing rip static-neighbor",
  "/routing route",
  "/routing rpki",
  "/routing rpki session",
  "/routing rule",
  "/routing settings",
  "/routing stats",
  "/routing stats memory",
  "/routing stats origin",
  "/routing stats pcap",
  "/routing stats process",
  "/routing stats step",
  "/routing table",
  "/safe-mode",
  "/smb",
  "/snmp",
  "/snmp community",
  "/special-login",
  "/system",
  "/system backup",
  "/system backup cloud",
  "/system clock",
  "/system clock manual",
];
